"""initial schema

Revision ID: 543d5ad5f546
Revises: 
Create Date: 2026-08-25 10:17:37.639994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543d5ad5f546'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('client_code', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('pan_masked', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('kyc_status', sa.String(), server_default=sa.text("'Verified'"), nullable=False),
    sa.Column('kyc_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'Up'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Up', 'Down')", name='ck_clients_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_code'), 'clients', ['client_code'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_owner_id'), 'clients', ['owner_id'], unique=False)
    op.create_index('ix_clients_owner_is_demo', 'clients', ['owner_id', 'is_demo'], unique=False)
    op.create_table('funds_check_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('actual_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('required_funds', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('surplus', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_check_logs_id'), 'funds_check_logs', ['id'], unique=False)
    op.create_index(op.f('ix_funds_check_logs_owner_id'), 'funds_check_logs', ['owner_id'], unique=False)
    op.create_table('margin_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('stock', sa.String(), nullable=False),
    sa.Column('trade_type', sa.String(), nullable=False),
    sa.Column('margin_required', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_available', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("margin_status IN ('OK', 'issue')", name='ck_margin_trades_margin_status'),
    sa.CheckConstraint("trade_type IN ('BUY', 'SELL')", name='ck_margin_trades_trade_type'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_margin_trades_client_id'), 'margin_trades', ['client_id'], unique=False)
    op.create_index(op.f('ix_margin_trades_id'), 'margin_trades', ['id'], unique=False)
    op.create_index(op.f('ix_margin_trades_owner_id'), 'margin_trades', ['owner_id'], unique=False)
    op.create_index('ix_margin_trades_owner_is_demo', 'margin_trades', ['owner_id', 'is_demo'], unique=False)
    op.create_table('watchdog_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('stock', sa.String(), nullable=False),
    sa.Column('trade_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("trade_type IN ('BUY', 'SELL')", name='ck_watchdog_trades_trade_type'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchdog_trades_client_id'), 'watchdog_trades', ['client_id'], unique=False)
    op.create_index(op.f('ix_watchdog_trades_id'), 'watchdog_trades', ['id'], unique=False)
    op.create_index(op.f('ix_watchdog_trades_owner_id'), 'watchdog_trades', ['owner_id'], unique=False)
    op.create_index('ix_watchdog_trades_owner_is_demo', 'watchdog_trades', ['owner_id', 'is_demo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchdog_trades_owner_is_demo', table_name='watchdog_trades')
    op.drop_index(op.f('ix_watchdog_trades_owner_id'), table_name='watchdog_trades')
    op.drop_index(op.f('ix_watchdog_trades_id'), table_name='watchdog_trades')
    op.drop_index(op.f('ix_watchdog_trades_client_id'), table_name='watchdog_trades')
    op.drop_table('watchdog_trades')
    op.drop_index('ix_margin_trades_owner_is_demo', table_name='margin_trades')
    op.drop_index(op.f('ix_margin_trades_owner_id'), table_name='margin_trades')
    op.drop_index(op.f('ix_margin_trades_id'), table_name='margin_trades')
    op.drop_index(op.f('ix_margin_trades_client_id'), table_name='margin_trades')
    op.drop_table('margin_trades')
    op.drop_index(op.f('ix_funds_check_logs_owner_id'), table_name='funds_check_logs')
    op.drop_index(op.f('ix_funds_check_logs_id'), table_name='funds_check_logs')
    op.drop_table('funds_check_logs')
    op.drop_index('ix_clients_owner_is_demo', table_name='clients')
    op.drop_index(op.f('ix_clients_owner_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
